### ISSUE TITLE
Handling redundant factors and singletons

### ISSUE THREAD

**Issue by Nosferican** [FixedEffects/FixedEffects.jl#4]
This question / feature request is pertains to obtaining a sensible estimate for the degrees of freedom consumed by the transformation. For example, reghdfe computes redundant levels by cumulative dimension though being a weak subset of another. Singletons are eliminated iteratively and purged until no singletons remain.

**Comment by matthieugomez** [comment]
Note that reghdfe only uses one iteration. In this case, the code is very simple:
```
function drop_singletons!(esample, fe::FixedEffect)
    cache = zeros(Int, fe.n)
    for i in eachindex(esample)
        if esample[i]
            cache[fe.refs[i]] += 1
        end
    end
    for i in eachindex(esample)
        if esample[i] & cache[fe.refs[i]] <= 1
            esample[i] = false
        end
    end
end
esample = trues(N)
for fe in fes
    drop_singletons!(esample, fe::FixedEffect)
end
```
