### ISSUE TITLE
Precision since 2.0.4

### ISSUE THREAD

**Issue by jmboehm** [FixedEffects/FixedEffects.jl#52]
Hi Matthieu,

When trying to update GLFixedEffectModels to use FixedEffects >= 2.0.4, I've noticed that some tests do no longer pass when I do that. The estimates (particular of the VCov) are numerically different, and increasing the `center_tol` does not seem to help. The estimates [Alpaca](https://cran.r-project.org/web/packages/alpaca/alpaca.pdf) gives with low tolerances are much closer to the ones from < 2.0.4.  

This is happening with the CPU solver (I don't have a suitable GPU here to try out), and on toy datasets (iris). Do you have an idea what could be the reason? To me it seems that something in #47 must have caused this.

Thanks and best,
Johannes

**Comment by matthieugomez** [comment]
Thanks. Fixed with 2.1 and added a test to check for this in the future.
